default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: internship_challenge_development
test:
  <<: *default
  database: internship_challenge_test

production:
  <<: *default
  database: internship_challenge_production
  username: internship_challenge
  password: <%= ENV['INTERNSHIP_CHALLENGE_DATABASE_PASSWORD'] %>
